//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public empleados()
        {
            this.vinculaciones = new HashSet<vinculaciones>();
        }
    
        public string idEmpleado { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoS { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string LugarNacimiento { get; set; }
        public string Direccion { get; set; }
        public Nullable<long> Telefono { get; set; }
        public Nullable<long> Celular { get; set; }
        public string GrupoSanguineo { get; set; }
        public string Profesion { get; set; }
    
        public virtual fotos fotos { get; set; }
        public virtual ICollection<vinculaciones> vinculaciones { get; set; }
    }
}
