//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nominashcEntities : DbContext
    {
        public nominashcEntities()
            : base("name=nominashcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<arl> arl { get; set; }
        public DbSet<bancos> bancos { get; set; }
        public DbSet<cargos> cargos { get; set; }
        public DbSet<ccf> ccf { get; set; }
        public DbSet<departamentos> departamentos { get; set; }
        public DbSet<empleados> empleados { get; set; }
        public DbSet<empresas> empresas { get; set; }
        public DbSet<eps> eps { get; set; }
        public DbSet<fotos> fotos { get; set; }
        public DbSet<novedades> novedades { get; set; }
        public DbSet<pension> pension { get; set; }
        public DbSet<tiponovedad> tiponovedad { get; set; }
        public DbSet<vinculaciones> vinculaciones { get; set; }
    }
}
