//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentas
    {
        public cuentas()
        {
            this.vinculaciones = new HashSet<vinculaciones>();
        }
    
        public string NoCuenta { get; set; }
        public string TipoCuenta { get; set; }
        public string NitBanco { get; set; }
    
        public virtual bancos bancos { get; set; }
        public virtual ICollection<vinculaciones> vinculaciones { get; set; }
    }
}
