//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleadoempresa
    {
        public empleadoempresa()
        {
            this.vinculaciones = new HashSet<vinculaciones>();
        }
    
        public int idEmpleado { get; set; }
        public int idEmpresa { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual ICollection<vinculaciones> vinculaciones { get; set; }
    }
}
