//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vinculaciones
    {
        public int idVinculacion { get; set; }
        public int idCargos { get; set; }
        public int idARL { get; set; }
        public int idEPS { get; set; }
        public int idPension { get; set; }
        public int idCCF { get; set; }
        public int idEmpleado { get; set; }
        public int idEmpresa { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public string TipoContrato { get; set; }
        public string PeriodoPago { get; set; }
        public Nullable<long> Salario { get; set; }
        public int NoCuenta { get; set; }
    
        public virtual arl arl { get; set; }
        public virtual cargos cargos { get; set; }
        public virtual ccf ccf { get; set; }
        public virtual cuentas cuentas { get; set; }
        public virtual empleadoempresa empleadoempresa { get; set; }
        public virtual eps eps { get; set; }
        public virtual pension pension { get; set; }
    }
}
